#ifndef __BSP_GPIO_H
#define __BSP_GPIO_H
#include "Common/base_inc.h"
#include <stdint.h>


/* GPIO引脚位置宏定义  */
#define 	gpioPin0    	1<<0
#define 	gpioPin1    	1<<1
#define 	gpioPin2    	1<<2
#define 	gpioPin3    	1<<3
#define 	gpioPin4    	1<<4
#define 	gpioPin5    	1<<5
#define 	gpioPin6    	1<<6
#define 	gpioPin7    	1<<7
#define 	gpioPin8    	1<<8
#define 	gpioPin9    	1<<9
#define 	gpioPin10    	1<<10
#define 	gpioPin11    	1<<11
#define 	gpioPin12    	1<<12
#define 	gpioPin13    	1<<13
#define 	gpioPin14    	1<<14
#define 	gpioPin15    	1<<15


/********************************IO状态读取宏**************************************/
#define 	IN_PUT_A0  		SYS_GPIO_PIN_Get(GPIOA, gpioPin0)    
#define 	IN_PUT_A1  		SYS_GPIO_PIN_Get(GPIOA, gpioPin1) 
#define 	IN_PUT_A2  		SYS_GPIO_PIN_Get(GPIOA, gpioPin2) 
#define 	IN_PUT_A3  		SYS_GPIO_PIN_Get(GPIOA, gpioPin3) 
#define 	IN_PUT_A4  		SYS_GPIO_PIN_Get(GPIOA, gpioPin4) 
#define 	IN_PUT_A5  		SYS_GPIO_PIN_Get(GPIOA, gpioPin5) 
#define 	IN_PUT_A6  		SYS_GPIO_PIN_Get(GPIOA, gpioPin6) 
#define 	IN_PUT_A7  		SYS_GPIO_PIN_Get(GPIOA, gpioPin7) 
#define 	IN_PUT_A8  		SYS_GPIO_PIN_Get(GPIOA, gpioPin8) 
#define 	IN_PUT_A9  		SYS_GPIO_PIN_Get(GPIOA, gpioPin9) 
#define 	IN_PUT_A10 		SYS_GPIO_PIN_Get(GPIOA, gpioPin10) 
#define 	IN_PUT_A11		SYS_GPIO_PIN_Get(GPIOA, gpioPin11) 
#define 	IN_PUT_A12      SYS_GPIO_PIN_Get(GPIOA, gpioPin12) 
#define 	IN_PUT_A13      SYS_GPIO_PIN_Get(GPIOA, gpioPin13) 
#define 	IN_PUT_A14      SYS_GPIO_PIN_Get(GPIOA, gpioPin14) 
#define 	IN_PUT_A15      SYS_GPIO_PIN_Get(GPIOA, gpioPin15) 

#define 	IN_PUT_B0  		SYS_GPIO_PIN_Get(GPIOB, gpioPin0)    
#define 	IN_PUT_B1  		SYS_GPIO_PIN_Get(GPIOB, gpioPin1) 
#define 	IN_PUT_B2  		SYS_GPIO_PIN_Get(GPIOB, gpioPin2) 
#define 	IN_PUT_B3  		SYS_GPIO_PIN_Get(GPIOB, gpioPin3) 
#define 	IN_PUT_B4  		SYS_GPIO_PIN_Get(GPIOB, gpioPin4) 
#define 	IN_PUT_B5  		SYS_GPIO_PIN_Get(GPIOB, gpioPin5) 
#define 	IN_PUT_B6  		SYS_GPIO_PIN_Get(GPIOB, gpioPin6) 
#define 	IN_PUT_B7  		SYS_GPIO_PIN_Get(GPIOB, gpioPin7) 
#define 	IN_PUT_B8  		SYS_GPIO_PIN_Get(GPIOB, gpioPin8) 
#define 	IN_PUT_B9  		SYS_GPIO_PIN_Get(GPIOB, gpioPin9) 
#define 	IN_PUT_B10 		SYS_GPIO_PIN_Get(GPIOB, gpioPin10) 
#define 	IN_PUT_B11		SYS_GPIO_PIN_Get(GPIOB, gpioPin11) 
#define 	IN_PUT_B12      SYS_GPIO_PIN_Get(GPIOB, gpioPin12) 
#define 	IN_PUT_B13      SYS_GPIO_PIN_Get(GPIOB, gpioPin13) 
#define 	IN_PUT_B14      SYS_GPIO_PIN_Get(GPIOB, gpioPin14) 
#define 	IN_PUT_B15      SYS_GPIO_PIN_Get(GPIOB, gpioPin15) 

#define 	IN_PUT_C0  		SYS_GPIO_PIN_Get(GPIOC, gpioPin0)    
#define 	IN_PUT_C1  		SYS_GPIO_PIN_Get(GPIOC, gpioPin1) 
#define 	IN_PUT_C2  		SYS_GPIO_PIN_Get(GPIOC, gpioPin2) 
#define 	IN_PUT_C3  		SYS_GPIO_PIN_Get(GPIOC, gpioPin3) 
#define 	IN_PUT_C4  		SYS_GPIO_PIN_Get(GPIOC, gpioPin4) 
#define 	IN_PUT_C5  		SYS_GPIO_PIN_Get(GPIOC, gpioPin5) 
#define 	IN_PUT_C6  		SYS_GPIO_PIN_Get(GPIOC, gpioPin6) 
#define 	IN_PUT_C7  		SYS_GPIO_PIN_Get(GPIOC, gpioPin7) 
#define 	IN_PUT_C8  		SYS_GPIO_PIN_Get(GPIOC, gpioPin8) 
#define 	IN_PUT_C9  		SYS_GPIO_PIN_Get(GPIOC, gpioPin9) 
#define 	IN_PUT_C10 		SYS_GPIO_PIN_Get(GPIOC, gpioPin10) 
#define 	IN_PUT_C11		SYS_GPIO_PIN_Get(GPIOC, gpioPin11) 
#define 	IN_PUT_C12      SYS_GPIO_PIN_Get(GPIOC, gpioPin12) 
#define 	IN_PUT_C13      SYS_GPIO_PIN_Get(GPIOC, gpioPin13) 
#define 	IN_PUT_C14      SYS_GPIO_PIN_Get(GPIOC, gpioPin14) 
#define 	IN_PUT_C15      SYS_GPIO_PIN_Get(GPIOC, gpioPin15) 

#define 	IN_PUT_D0  		SYS_GPIO_PIN_Get(GPIOD, gpioPin0)    
#define 	IN_PUT_D1  		SYS_GPIO_PIN_Get(GPIOD, gpioPin1) 
#define 	IN_PUT_D2  		SYS_GPIO_PIN_Get(GPIOD, gpioPin2) 
#define 	IN_PUT_D3  		SYS_GPIO_PIN_Get(GPIOD, gpioPin3) 
#define 	IN_PUT_D4  		SYS_GPIO_PIN_Get(GPIOD, gpioPin4) 
#define 	IN_PUT_D5  		SYS_GPIO_PIN_Get(GPIOD, gpioPin5) 
#define 	IN_PUT_D6  		SYS_GPIO_PIN_Get(GPIOD, gpioPin6) 
#define 	IN_PUT_D7  		SYS_GPIO_PIN_Get(GPIOD, gpioPin7) 
#define 	IN_PUT_D8  		SYS_GPIO_PIN_Get(GPIOD, gpioPin8) 
#define 	IN_PUT_D9  		SYS_GPIO_PIN_Get(GPIOD, gpioPin9) 
#define 	IN_PUT_D10 		SYS_GPIO_PIN_Get(GPIOD, gpioPin10) 
#define 	IN_PUT_D11		SYS_GPIO_PIN_Get(GPIOD, gpioPin11) 
#define 	IN_PUT_D12      SYS_GPIO_PIN_Get(GPIOD, gpioPin12) 
#define 	IN_PUT_D13      SYS_GPIO_PIN_Get(GPIOD, gpioPin13) 
#define 	IN_PUT_D14      SYS_GPIO_PIN_Get(GPIOD, gpioPin14) 
#define 	IN_PUT_D15      SYS_GPIO_PIN_Get(GPIOD, gpioPin15) 


#define 	IN_PUT_E0  		SYS_GPIO_PIN_Get(GPIOE, gpioPin0)    
#define 	IN_PUT_E1  		SYS_GPIO_PIN_Get(GPIOE, gpioPin1) 
#define 	IN_PUT_E2  		SYS_GPIO_PIN_Get(GPIOE, gpioPin2) 
#define 	IN_PUT_E3  		SYS_GPIO_PIN_Get(GPIOE, gpioPin3) 
#define 	IN_PUT_E4  		SYS_GPIO_PIN_Get(GPIOE, gpioPin4) 
#define 	IN_PUT_E5  		SYS_GPIO_PIN_Get(GPIOE, gpioPin5) 
#define 	IN_PUT_E6  		SYS_GPIO_PIN_Get(GPIOE, gpioPin6) 
#define 	IN_PUT_E7  		SYS_GPIO_PIN_Get(GPIOE, gpioPin7) 
#define 	IN_PUT_E8  		SYS_GPIO_PIN_Get(GPIOE, gpioPin8) 
#define 	IN_PUT_E9  		SYS_GPIO_PIN_Get(GPIOE, gpioPin9) 
#define 	IN_PUT_E10 		SYS_GPIO_PIN_Get(GPIOE, gpioPin10) 
#define 	IN_PUT_E11		SYS_GPIO_PIN_Get(GPIOE, gpioPin11) 
#define 	IN_PUT_E12      SYS_GPIO_PIN_Get(GPIOE, gpioPin12) 
#define 	IN_PUT_E13      SYS_GPIO_PIN_Get(GPIOE, gpioPin13) 
#define 	IN_PUT_E14      SYS_GPIO_PIN_Get(GPIOE, gpioPin14) 
#define 	IN_PUT_E15      SYS_GPIO_PIN_Get(GPIOE, gpioPin15) 


#define 	IN_PUT_F0  		SYS_GPIO_PIN_Get(GPIOF, gpioPin0)    
#define 	IN_PUT_F1  		SYS_GPIO_PIN_Get(GPIOF, gpioPin1) 
#define 	IN_PUT_F2  		SYS_GPIO_PIN_Get(GPIOF, gpioPin2) 
#define 	IN_PUT_F3  		SYS_GPIO_PIN_Get(GPIOF, gpioPin3) 
#define 	IN_PUT_F4  		SYS_GPIO_PIN_Get(GPIOF, gpioPin4) 
#define 	IN_PUT_F5  		SYS_GPIO_PIN_Get(GPIOF, gpioPin5) 
#define 	IN_PUT_F6  		SYS_GPIO_PIN_Get(GPIOF, gpioPin6) 
#define 	IN_PUT_F7  		SYS_GPIO_PIN_Get(GPIOF, gpioPin7) 
#define 	IN_PUT_F8  		SYS_GPIO_PIN_Get(GPIOF, gpioPin8) 
#define 	IN_PUT_F9  		SYS_GPIO_PIN_Get(GPIOF, gpioPin9) 
#define 	IN_PUT_F10 		SYS_GPIO_PIN_Get(GPIOF, gpioPin10) 
#define 	IN_PUT_F11		SYS_GPIO_PIN_Get(GPIOF, gpioPin11) 
#define 	IN_PUT_F12      SYS_GPIO_PIN_Get(GPIOF, gpioPin12) 
#define 	IN_PUT_F13      SYS_GPIO_PIN_Get(GPIOF, gpioPin13) 
#define 	IN_PUT_F14      SYS_GPIO_PIN_Get(GPIOF, gpioPin14) 
#define 	IN_PUT_F15      SYS_GPIO_PIN_Get(GPIOF, gpioPin15) 

#define 	IN_PUT_G0  		SYS_GPIO_PIN_Get(GPIOG, gpioPin0)    
#define 	IN_PUT_G1  		SYS_GPIO_PIN_Get(GPIOG, gpioPin1) 
#define 	IN_PUT_G2  		SYS_GPIO_PIN_Get(GPIOG, gpioPin2) 
#define 	IN_PUT_G3  		SYS_GPIO_PIN_Get(GPIOG, gpioPin3) 
#define 	IN_PUT_G4  		SYS_GPIO_PIN_Get(GPIOG, gpioPin4) 
#define 	IN_PUT_G5  		SYS_GPIO_PIN_Get(GPIOG, gpioPin5) 
#define 	IN_PUT_G6  		SYS_GPIO_PIN_Get(GPIOG, gpioPin6) 
#define 	IN_PUT_G7  		SYS_GPIO_PIN_Get(GPIOG, gpioPin7) 
#define 	IN_PUT_G8  		SYS_GPIO_PIN_Get(GPIOG, gpioPin8) 
#define 	IN_PUT_G9  		SYS_GPIO_PIN_Get(GPIOG, gpioPin9) 
#define 	IN_PUT_G10 		SYS_GPIO_PIN_Get(GPIOG, gpioPin10) 
#define 	IN_PUT_G11		SYS_GPIO_PIN_Get(GPIOG, gpioPin11) 
#define 	IN_PUT_G12      SYS_GPIO_PIN_Get(GPIOG, gpioPin12) 
#define 	IN_PUT_G13      SYS_GPIO_PIN_Get(GPIOG, gpioPin13) 
#define 	IN_PUT_G14      SYS_GPIO_PIN_Get(GPIOG, gpioPin14) 
#define 	IN_PUT_G15      SYS_GPIO_PIN_Get(GPIOG, gpioPin15) 

#define 	IN_PUT_H0  		SYS_GPIO_PIN_Get(GPIOH, gpioPin0)    
#define 	IN_PUT_H1  		SYS_GPIO_PIN_Get(GPIOH, gpioPin1) 
#define 	IN_PUT_H2  		SYS_GPIO_PIN_Get(GPIOH, gpioPin2) 
#define 	IN_PUT_H3  		SYS_GPIO_PIN_Get(GPIOH, gpioPin3) 
#define 	IN_PUT_H4  		SYS_GPIO_PIN_Get(GPIOH, gpioPin4) 
#define 	IN_PUT_H5  		SYS_GPIO_PIN_Get(GPIOH, gpioPin5) 
#define 	IN_PUT_H6  		SYS_GPIO_PIN_Get(GPIOH, gpioPin6) 
#define 	IN_PUT_H7  		SYS_GPIO_PIN_Get(GPIOH, gpioPin7) 
#define 	IN_PUT_H8  		SYS_GPIO_PIN_Get(GPIOH, gpioPin8) 
#define 	IN_PUT_H9  		SYS_GPIO_PIN_Get(GPIOH, gpioPin9) 
#define 	IN_PUT_H10 		SYS_GPIO_PIN_Get(GPIOH, gpioPin10) 
#define 	IN_PUT_H11		SYS_GPIO_PIN_Get(GPIOH, gpioPin11) 
#define 	IN_PUT_H12      SYS_GPIO_PIN_Get(GPIOH, gpioPin12) 
#define 	IN_PUT_H13      SYS_GPIO_PIN_Get(GPIOH, gpioPin13) 
#define 	IN_PUT_H14      SYS_GPIO_PIN_Get(GPIOH, gpioPin14) 
#define 	IN_PUT_H15      SYS_GPIO_PIN_Get(GPIOH, gpioPin15) 

#define 	IN_PUT_I0  		SYS_GPIO_PIN_Get(GPIOI, gpioPin0)    
#define 	IN_PUT_I1  		SYS_GPIO_PIN_Get(GPIOI, gpioPin1) 
#define 	IN_PUT_I2  		SYS_GPIO_PIN_Get(GPIOI, gpioPin2) 
#define 	IN_PUT_I3  		SYS_GPIO_PIN_Get(GPIOI, gpioPin3) 
#define 	IN_PUT_I4  		SYS_GPIO_PIN_Get(GPIOI, gpioPin4) 
#define 	IN_PUT_I5  		SYS_GPIO_PIN_Get(GPIOI, gpioPin5) 
#define 	IN_PUT_I6  		SYS_GPIO_PIN_Get(GPIOI, gpioPin6) 
#define 	IN_PUT_I7  		SYS_GPIO_PIN_Get(GPIOI, gpioPin7) 
#define 	IN_PUT_I8  		SYS_GPIO_PIN_Get(GPIOI, gpioPin8) 
#define 	IN_PUT_I9  		SYS_GPIO_PIN_Get(GPIOI, gpioPin9) 
#define 	IN_PUT_I10 		SYS_GPIO_PIN_Get(GPIOI, gpioPin10) 
#define 	IN_PUT_I11		SYS_GPIO_PIN_Get(GPIOI, gpioPin11) 
#define 	IN_PUT_I12      SYS_GPIO_PIN_Get(GPIOI, gpioPin12) 
#define 	IN_PUT_I13      SYS_GPIO_PIN_Get(GPIOI, gpioPin13) 
#define 	IN_PUT_I14      SYS_GPIO_PIN_Get(GPIOI, gpioPin14) 
#define 	IN_PUT_I15      SYS_GPIO_PIN_Get(GPIOI, gpioPin15) 


/************************************IO输出高电平宏***************************************/
#define 	OUT_PUT_HIGH_A0  		SYS_GPIO_PIN_Set(GPIOA, gpioPin0  , 0x01)    
#define 	OUT_PUT_HIGH_A1  		SYS_GPIO_PIN_Set(GPIOA, gpioPin1  , 0x01)    
#define 	OUT_PUT_HIGH_A2  		SYS_GPIO_PIN_Set(GPIOA, gpioPin2  , 0x01)    
#define 	OUT_PUT_HIGH_A3  		SYS_GPIO_PIN_Set(GPIOA, gpioPin3  , 0x01)    
#define 	OUT_PUT_HIGH_A4  		SYS_GPIO_PIN_Set(GPIOA, gpioPin4  , 0x01)    
#define 	OUT_PUT_HIGH_A5  		SYS_GPIO_PIN_Set(GPIOA, gpioPin5  , 0x01)    
#define 	OUT_PUT_HIGH_A6  		SYS_GPIO_PIN_Set(GPIOA, gpioPin6  , 0x01)    
#define 	OUT_PUT_HIGH_A7  		SYS_GPIO_PIN_Set(GPIOA, gpioPin7  , 0x01)    
#define 	OUT_PUT_HIGH_A8  		SYS_GPIO_PIN_Set(GPIOA, gpioPin8  , 0x01)    
#define 	OUT_PUT_HIGH_A9  		SYS_GPIO_PIN_Set(GPIOA, gpioPin9  , 0x01)    
#define 	OUT_PUT_HIGH_A10 		SYS_GPIO_PIN_Set(GPIOA, gpioPin10 , 0x01)    
#define 	OUT_PUT_HIGH_A11		SYS_GPIO_PIN_Set(GPIOA, gpioPin11 , 0x01)    
#define 	OUT_PUT_HIGH_A12      	SYS_GPIO_PIN_Set(GPIOA, gpioPin12 , 0x01)    
#define 	OUT_PUT_HIGH_A13      	SYS_GPIO_PIN_Set(GPIOA, gpioPin13 , 0x01)    
#define 	OUT_PUT_HIGH_A14      	SYS_GPIO_PIN_Set(GPIOA, gpioPin14 , 0x01)    
#define 	OUT_PUT_HIGH_A15      	SYS_GPIO_PIN_Set(GPIOA, gpioPin15 , 0x01)    
				   
#define 	OUT_PUT_HIGH_B0  		SYS_GPIO_PIN_Set(GPIOB, gpioPin0  , 0x01)    
#define 	OUT_PUT_HIGH_B1  		SYS_GPIO_PIN_Set(GPIOB, gpioPin1  , 0x01)    
#define 	OUT_PUT_HIGH_B2  		SYS_GPIO_PIN_Set(GPIOB, gpioPin2  , 0x01)    
#define 	OUT_PUT_HIGH_B3  		SYS_GPIO_PIN_Set(GPIOB, gpioPin3  , 0x01)    
#define 	OUT_PUT_HIGH_B4  		SYS_GPIO_PIN_Set(GPIOB, gpioPin4  , 0x01)    
#define 	OUT_PUT_HIGH_B5  		SYS_GPIO_PIN_Set(GPIOB, gpioPin5  , 0x01)    
#define 	OUT_PUT_HIGH_B6  		SYS_GPIO_PIN_Set(GPIOB, gpioPin6  , 0x01)    
#define 	OUT_PUT_HIGH_B7  		SYS_GPIO_PIN_Set(GPIOB, gpioPin7  , 0x01)    
#define 	OUT_PUT_HIGH_B8  		SYS_GPIO_PIN_Set(GPIOB, gpioPin8  , 0x01)    
#define 	OUT_PUT_HIGH_B9  		SYS_GPIO_PIN_Set(GPIOB, gpioPin9  , 0x01)    
#define 	OUT_PUT_HIGH_B10 		SYS_GPIO_PIN_Set(GPIOB, gpioPin10 , 0x01)    
#define 	OUT_PUT_HIGH_B11		SYS_GPIO_PIN_Set(GPIOB, gpioPin11 , 0x01)    
#define 	OUT_PUT_HIGH_B12      	SYS_GPIO_PIN_Set(GPIOB, gpioPin12 , 0x01)    
#define 	OUT_PUT_HIGH_B13      	SYS_GPIO_PIN_Set(GPIOB, gpioPin13 , 0x01)    
#define 	OUT_PUT_HIGH_B14      	SYS_GPIO_PIN_Set(GPIOB, gpioPin14 , 0x01)    
#define 	OUT_PUT_HIGH_B15      	SYS_GPIO_PIN_Set(GPIOB, gpioPin15 , 0x01)
				   
#define 	OUT_PUT_HIGH_C0  		SYS_GPIO_PIN_Set(GPIOC, gpioPin0  , 0x01)    
#define 	OUT_PUT_HIGH_C1  		SYS_GPIO_PIN_Set(GPIOC, gpioPin1  , 0x01)    
#define 	OUT_PUT_HIGH_C2  		SYS_GPIO_PIN_Set(GPIOC, gpioPin2  , 0x01)    
#define 	OUT_PUT_HIGH_C3  		SYS_GPIO_PIN_Set(GPIOC, gpioPin3  , 0x01)    
#define 	OUT_PUT_HIGH_C4  		SYS_GPIO_PIN_Set(GPIOC, gpioPin4  , 0x01)    
#define 	OUT_PUT_HIGH_C5  		SYS_GPIO_PIN_Set(GPIOC, gpioPin5  , 0x01)    
#define 	OUT_PUT_HIGH_C6  		SYS_GPIO_PIN_Set(GPIOC, gpioPin6  , 0x01)    
#define 	OUT_PUT_HIGH_C7  		SYS_GPIO_PIN_Set(GPIOC, gpioPin7  , 0x01)    
#define 	OUT_PUT_HIGH_C8  		SYS_GPIO_PIN_Set(GPIOC, gpioPin8  , 0x01)    
#define 	OUT_PUT_HIGH_C9  		SYS_GPIO_PIN_Set(GPIOC, gpioPin9  , 0x01)    
#define 	OUT_PUT_HIGH_C10 		SYS_GPIO_PIN_Set(GPIOC, gpioPin10 , 0x01)    
#define 	OUT_PUT_HIGH_C11		SYS_GPIO_PIN_Set(GPIOC, gpioPin11 , 0x01)    
#define 	OUT_PUT_HIGH_C12      	SYS_GPIO_PIN_Set(GPIOC, gpioPin12 , 0x01)    
#define 	OUT_PUT_HIGH_C13      	SYS_GPIO_PIN_Set(GPIOC, gpioPin13 , 0x01)    
#define 	OUT_PUT_HIGH_C14      	SYS_GPIO_PIN_Set(GPIOC, gpioPin14 , 0x01)    
#define 	OUT_PUT_HIGH_C15      	SYS_GPIO_PIN_Set(GPIOC, gpioPin15 , 0x01)
				   
#define 	OUT_PUT_HIGH_D0  		SYS_GPIO_PIN_Set(GPIOD, gpioPin0  , 0x01)    
#define 	OUT_PUT_HIGH_D1  		SYS_GPIO_PIN_Set(GPIOD, gpioPin1  , 0x01)    
#define 	OUT_PUT_HIGH_D2  		SYS_GPIO_PIN_Set(GPIOD, gpioPin2  , 0x01)    
#define 	OUT_PUT_HIGH_D3  		SYS_GPIO_PIN_Set(GPIOD, gpioPin3  , 0x01)    
#define 	OUT_PUT_HIGH_D4  		SYS_GPIO_PIN_Set(GPIOD, gpioPin4  , 0x01)    
#define 	OUT_PUT_HIGH_D5  		SYS_GPIO_PIN_Set(GPIOD, gpioPin5  , 0x01)    
#define 	OUT_PUT_HIGH_D6  		SYS_GPIO_PIN_Set(GPIOD, gpioPin6  , 0x01)    
#define 	OUT_PUT_HIGH_D7  		SYS_GPIO_PIN_Set(GPIOD, gpioPin7  , 0x01)    
#define 	OUT_PUT_HIGH_D8  		SYS_GPIO_PIN_Set(GPIOD, gpioPin8  , 0x01)    
#define 	OUT_PUT_HIGH_D9  		SYS_GPIO_PIN_Set(GPIOD, gpioPin9  , 0x01)    
#define 	OUT_PUT_HIGH_D10 		SYS_GPIO_PIN_Set(GPIOD, gpioPin10 , 0x01)    
#define 	OUT_PUT_HIGH_D11		SYS_GPIO_PIN_Set(GPIOD, gpioPin11 , 0x01)    
#define 	OUT_PUT_HIGH_D12      	SYS_GPIO_PIN_Set(GPIOD, gpioPin12 , 0x01)    
#define 	OUT_PUT_HIGH_D13      	SYS_GPIO_PIN_Set(GPIOD, gpioPin13 , 0x01)    
#define 	OUT_PUT_HIGH_D14      	SYS_GPIO_PIN_Set(GPIOD, gpioPin14 , 0x01)    
#define 	OUT_PUT_HIGH_D15      	SYS_GPIO_PIN_Set(GPIOD, gpioPin15 , 0x01)
				   
#define 	OUT_PUT_HIGH_E0  		SYS_GPIO_PIN_Set(GPIOE, gpioPin0  , 0x01)    
#define 	OUT_PUT_HIGH_E1  		SYS_GPIO_PIN_Set(GPIOE, gpioPin1  , 0x01)    
#define 	OUT_PUT_HIGH_E2  		SYS_GPIO_PIN_Set(GPIOE, gpioPin2  , 0x01)    
#define 	OUT_PUT_HIGH_E3  		SYS_GPIO_PIN_Set(GPIOE, gpioPin3  , 0x01)    
#define 	OUT_PUT_HIGH_E4  		SYS_GPIO_PIN_Set(GPIOE, gpioPin4  , 0x01)    
#define 	OUT_PUT_HIGH_E5  		SYS_GPIO_PIN_Set(GPIOE, gpioPin5  , 0x01)    
#define 	OUT_PUT_HIGH_E6  		SYS_GPIO_PIN_Set(GPIOE, gpioPin6  , 0x01)    
#define 	OUT_PUT_HIGH_E7  		SYS_GPIO_PIN_Set(GPIOE, gpioPin7  , 0x01)    
#define 	OUT_PUT_HIGH_E8  		SYS_GPIO_PIN_Set(GPIOE, gpioPin8  , 0x01)    
#define 	OUT_PUT_HIGH_E9  		SYS_GPIO_PIN_Set(GPIOE, gpioPin9  , 0x01)    
#define 	OUT_PUT_HIGH_E10 		SYS_GPIO_PIN_Set(GPIOE, gpioPin10 , 0x01)    
#define 	OUT_PUT_HIGH_E11		SYS_GPIO_PIN_Set(GPIOE, gpioPin11 , 0x01)    
#define 	OUT_PUT_HIGH_E12      	SYS_GPIO_PIN_Set(GPIOE, gpioPin12 , 0x01)    
#define 	OUT_PUT_HIGH_E13      	SYS_GPIO_PIN_Set(GPIOE, gpioPin13 , 0x01)    
#define 	OUT_PUT_HIGH_E14      	SYS_GPIO_PIN_Set(GPIOE, gpioPin14 , 0x01)    
#define 	OUT_PUT_HIGH_E15      	SYS_GPIO_PIN_Set(GPIOE, gpioPin15 , 0x01)
				   
#define 	OUT_PUT_HIGH_F0  		SYS_GPIO_PIN_Set(GPIOF, gpioPin0  , 0x01)    
#define 	OUT_PUT_HIGH_F1  		SYS_GPIO_PIN_Set(GPIOF, gpioPin1  , 0x01)    
#define 	OUT_PUT_HIGH_F2  		SYS_GPIO_PIN_Set(GPIOF, gpioPin2  , 0x01)    
#define 	OUT_PUT_HIGH_F3  		SYS_GPIO_PIN_Set(GPIOF, gpioPin3  , 0x01)    
#define 	OUT_PUT_HIGH_F4  		SYS_GPIO_PIN_Set(GPIOF, gpioPin4  , 0x01)    
#define 	OUT_PUT_HIGH_F5  		SYS_GPIO_PIN_Set(GPIOF, gpioPin5  , 0x01)    
#define 	OUT_PUT_HIGH_F6  		SYS_GPIO_PIN_Set(GPIOF, gpioPin6  , 0x01)    
#define 	OUT_PUT_HIGH_F7  		SYS_GPIO_PIN_Set(GPIOF, gpioPin7  , 0x01)    
#define 	OUT_PUT_HIGH_F8  		SYS_GPIO_PIN_Set(GPIOF, gpioPin8  , 0x01)    
#define 	OUT_PUT_HIGH_F9  		SYS_GPIO_PIN_Set(GPIOF, gpioPin9  , 0x01)    
#define 	OUT_PUT_HIGH_F10 		SYS_GPIO_PIN_Set(GPIOF, gpioPin10 , 0x01)    
#define 	OUT_PUT_HIGH_F11		SYS_GPIO_PIN_Set(GPIOF, gpioPin11 , 0x01)    
#define 	OUT_PUT_HIGH_F12      	SYS_GPIO_PIN_Set(GPIOF, gpioPin12 , 0x01)    
#define 	OUT_PUT_HIGH_F13      	SYS_GPIO_PIN_Set(GPIOF, gpioPin13 , 0x01)    
#define 	OUT_PUT_HIGH_F14      	SYS_GPIO_PIN_Set(GPIOF, gpioPin14 , 0x01)    
#define 	OUT_PUT_HIGH_F15      	SYS_GPIO_PIN_Set(GPIOF, gpioPin15 , 0x01)
				   
#define 	OUT_PUT_HIGH_G0  		SYS_GPIO_PIN_Set(GPIOG, gpioPin0  , 0x01)    
#define 	OUT_PUT_HIGH_G1  		SYS_GPIO_PIN_Set(GPIOG, gpioPin1  , 0x01)    
#define 	OUT_PUT_HIGH_G2  		SYS_GPIO_PIN_Set(GPIOG, gpioPin2  , 0x01)    
#define 	OUT_PUT_HIGH_G3  		SYS_GPIO_PIN_Set(GPIOG, gpioPin3  , 0x01)    
#define 	OUT_PUT_HIGH_G4  		SYS_GPIO_PIN_Set(GPIOG, gpioPin4  , 0x01)    
#define 	OUT_PUT_HIGH_G5  		SYS_GPIO_PIN_Set(GPIOG, gpioPin5  , 0x01)    
#define 	OUT_PUT_HIGH_G6  		SYS_GPIO_PIN_Set(GPIOG, gpioPin6  , 0x01)    
#define 	OUT_PUT_HIGH_G7  		SYS_GPIO_PIN_Set(GPIOG, gpioPin7  , 0x01)    
#define 	OUT_PUT_HIGH_G8  		SYS_GPIO_PIN_Set(GPIOG, gpioPin8  , 0x01)    
#define 	OUT_PUT_HIGH_G9  		SYS_GPIO_PIN_Set(GPIOG, gpioPin9  , 0x01)    
#define 	OUT_PUT_HIGH_G10 		SYS_GPIO_PIN_Set(GPIOG, gpioPin10 , 0x01)    
#define 	OUT_PUT_HIGH_G11		SYS_GPIO_PIN_Set(GPIOG, gpioPin11 , 0x01)    
#define 	OUT_PUT_HIGH_G12      	SYS_GPIO_PIN_Set(GPIOG, gpioPin12 , 0x01)    
#define 	OUT_PUT_HIGH_G13      	SYS_GPIO_PIN_Set(GPIOG, gpioPin13 , 0x01)    
#define 	OUT_PUT_HIGH_G14      	SYS_GPIO_PIN_Set(GPIOG, gpioPin14 , 0x01)    
#define 	OUT_PUT_HIGH_G15      	SYS_GPIO_PIN_Set(GPIOG, gpioPin15 , 0x01)
				   
#define 	OUT_PUT_HIGH_H0  		SYS_GPIO_PIN_Set(GPIOH, gpioPin0  , 0x01)    
#define 	OUT_PUT_HIGH_H1  		SYS_GPIO_PIN_Set(GPIOH, gpioPin1  , 0x01)    
#define 	OUT_PUT_HIGH_H2  		SYS_GPIO_PIN_Set(GPIOH, gpioPin2  , 0x01)    
#define 	OUT_PUT_HIGH_H3  		SYS_GPIO_PIN_Set(GPIOH, gpioPin3  , 0x01)    
#define 	OUT_PUT_HIGH_H4  		SYS_GPIO_PIN_Set(GPIOH, gpioPin4  , 0x01)    
#define 	OUT_PUT_HIGH_H5  		SYS_GPIO_PIN_Set(GPIOH, gpioPin5  , 0x01)    
#define 	OUT_PUT_HIGH_H6  		SYS_GPIO_PIN_Set(GPIOH, gpioPin6  , 0x01)    
#define 	OUT_PUT_HIGH_H7  		SYS_GPIO_PIN_Set(GPIOH, gpioPin7  , 0x01)    
#define 	OUT_PUT_HIGH_H8  		SYS_GPIO_PIN_Set(GPIOH, gpioPin8  , 0x01)    
#define 	OUT_PUT_HIGH_H9  		SYS_GPIO_PIN_Set(GPIOH, gpioPin9  , 0x01)    
#define 	OUT_PUT_HIGH_H10 		SYS_GPIO_PIN_Set(GPIOH, gpioPin10 , 0x01)    
#define 	OUT_PUT_HIGH_H11		SYS_GPIO_PIN_Set(GPIOH, gpioPin11 , 0x01)    
#define 	OUT_PUT_HIGH_H12      	SYS_GPIO_PIN_Set(GPIOH, gpioPin12 , 0x01)    
#define 	OUT_PUT_HIGH_H13      	SYS_GPIO_PIN_Set(GPIOH, gpioPin13 , 0x01)    
#define 	OUT_PUT_HIGH_H14      	SYS_GPIO_PIN_Set(GPIOH, gpioPin14 , 0x01)    
#define 	OUT_PUT_HIGH_H15      	SYS_GPIO_PIN_Set(GPIOH, gpioPin15 , 0x01)
				   
#define 	OUT_PUT_HIGH_I0  		SYS_GPIO_PIN_Set(GPIOI, gpioPin0  , 0x01)    
#define 	OUT_PUT_HIGH_I1  		SYS_GPIO_PIN_Set(GPIOI, gpioPin1  , 0x01)    
#define 	OUT_PUT_HIGH_I2  		SYS_GPIO_PIN_Set(GPIOI, gpioPin2  , 0x01)    
#define 	OUT_PUT_HIGH_I3  		SYS_GPIO_PIN_Set(GPIOI, gpioPin3  , 0x01)    
#define 	OUT_PUT_HIGH_I4  		SYS_GPIO_PIN_Set(GPIOI, gpioPin4  , 0x01)    
#define 	OUT_PUT_HIGH_I5  		SYS_GPIO_PIN_Set(GPIOI, gpioPin5  , 0x01)    
#define 	OUT_PUT_HIGH_I6  		SYS_GPIO_PIN_Set(GPIOI, gpioPin6  , 0x01)    
#define 	OUT_PUT_HIGH_I7  		SYS_GPIO_PIN_Set(GPIOI, gpioPin7  , 0x01)    
#define 	OUT_PUT_HIGH_I8  		SYS_GPIO_PIN_Set(GPIOI, gpioPin8  , 0x01)    
#define 	OUT_PUT_HIGH_I9  		SYS_GPIO_PIN_Set(GPIOI, gpioPin9  , 0x01)    
#define 	OUT_PUT_HIGH_I10 		SYS_GPIO_PIN_Set(GPIOI, gpioPin10 , 0x01)    
#define 	OUT_PUT_HIGH_I11		SYS_GPIO_PIN_Set(GPIOI, gpioPin11 , 0x01)    
#define 	OUT_PUT_HIGH_I12      	SYS_GPIO_PIN_Set(GPIOI, gpioPin12 , 0x01)    
#define 	OUT_PUT_HIGH_I13      	SYS_GPIO_PIN_Set(GPIOI, gpioPin13 , 0x01)    
#define 	OUT_PUT_HIGH_I14      	SYS_GPIO_PIN_Set(GPIOI, gpioPin14 , 0x01)    
#define 	OUT_PUT_HIGH_I15      	SYS_GPIO_PIN_Set(GPIOI, gpioPin15 , 0x01)


/************************************IO输出低电平宏***************************************/
#define 	OUT_PUT_LOW_A0  		SYS_GPIO_PIN_Set(GPIOA, gpioPin0  , 0x00)    
#define 	OUT_PUT_LOW_A1  		SYS_GPIO_PIN_Set(GPIOA, gpioPin1  , 0x00)    
#define 	OUT_PUT_LOW_A2  		SYS_GPIO_PIN_Set(GPIOA, gpioPin2  , 0x00)    
#define 	OUT_PUT_LOW_A3  		SYS_GPIO_PIN_Set(GPIOA, gpioPin3  , 0x00)    
#define 	OUT_PUT_LOW_A4  		SYS_GPIO_PIN_Set(GPIOA, gpioPin4  , 0x00)    
#define 	OUT_PUT_LOW_A5  		SYS_GPIO_PIN_Set(GPIOA, gpioPin5  , 0x00)    
#define 	OUT_PUT_LOW_A6  		SYS_GPIO_PIN_Set(GPIOA, gpioPin6  , 0x00)    
#define 	OUT_PUT_LOW_A7  		SYS_GPIO_PIN_Set(GPIOA, gpioPin7  , 0x00)    
#define 	OUT_PUT_LOW_A8  		SYS_GPIO_PIN_Set(GPIOA, gpioPin8  , 0x00)    
#define 	OUT_PUT_LOW_A9  		SYS_GPIO_PIN_Set(GPIOA, gpioPin9  , 0x00)    
#define 	OUT_PUT_LOW_A10 		SYS_GPIO_PIN_Set(GPIOA, gpioPin10 , 0x00)    
#define 	OUT_PUT_LOW_A11			SYS_GPIO_PIN_Set(GPIOA, gpioPin11 , 0x00)    
#define 	OUT_PUT_LOW_A12      	SYS_GPIO_PIN_Set(GPIOA, gpioPin12 , 0x00)    
#define 	OUT_PUT_LOW_A13      	SYS_GPIO_PIN_Set(GPIOA, gpioPin13 , 0x00)    
#define 	OUT_PUT_LOW_A14      	SYS_GPIO_PIN_Set(GPIOA, gpioPin14 , 0x00)    
#define 	OUT_PUT_LOW_A15      	SYS_GPIO_PIN_Set(GPIOA, gpioPin15 , 0x00)    
				   
#define 	OUT_PUT_LOW_B0  		SYS_GPIO_PIN_Set(GPIOB, gpioPin0  , 0x00)    
#define 	OUT_PUT_LOW_B1  		SYS_GPIO_PIN_Set(GPIOB, gpioPin1  , 0x00)    
#define 	OUT_PUT_LOW_B2  		SYS_GPIO_PIN_Set(GPIOB, gpioPin2  , 0x00)    
#define 	OUT_PUT_LOW_B3  		SYS_GPIO_PIN_Set(GPIOB, gpioPin3  , 0x00)    
#define 	OUT_PUT_LOW_B4  		SYS_GPIO_PIN_Set(GPIOB, gpioPin4  , 0x00)    
#define 	OUT_PUT_LOW_B5  		SYS_GPIO_PIN_Set(GPIOB, gpioPin5  , 0x00)    
#define 	OUT_PUT_LOW_B6  		SYS_GPIO_PIN_Set(GPIOB, gpioPin6  , 0x00)    
#define 	OUT_PUT_LOW_B7  		SYS_GPIO_PIN_Set(GPIOB, gpioPin7  , 0x00)    
#define 	OUT_PUT_LOW_B8  		SYS_GPIO_PIN_Set(GPIOB, gpioPin8  , 0x00)    
#define 	OUT_PUT_LOW_B9  		SYS_GPIO_PIN_Set(GPIOB, gpioPin9  , 0x00)    
#define 	OUT_PUT_LOW_B10 		SYS_GPIO_PIN_Set(GPIOB, gpioPin10 , 0x00)    
#define 	OUT_PUT_LOW_B11			SYS_GPIO_PIN_Set(GPIOB, gpioPin11 , 0x00)    
#define 	OUT_PUT_LOW_B12      	SYS_GPIO_PIN_Set(GPIOB, gpioPin12 , 0x00)    
#define 	OUT_PUT_LOW_B13      	SYS_GPIO_PIN_Set(GPIOB, gpioPin13 , 0x00)    
#define 	OUT_PUT_LOW_B14      	SYS_GPIO_PIN_Set(GPIOB, gpioPin14 , 0x00)    
#define 	OUT_PUT_LOW_B15      	SYS_GPIO_PIN_Set(GPIOB, gpioPin15 , 0x00)
				   
#define 	OUT_PUT_LOW_C0  		SYS_GPIO_PIN_Set(GPIOC, gpioPin0  , 0x00)    
#define 	OUT_PUT_LOW_C1  		SYS_GPIO_PIN_Set(GPIOC, gpioPin1  , 0x00)    
#define 	OUT_PUT_LOW_C2  		SYS_GPIO_PIN_Set(GPIOC, gpioPin2  , 0x00)    
#define 	OUT_PUT_LOW_C3  		SYS_GPIO_PIN_Set(GPIOC, gpioPin3  , 0x00)    
#define 	OUT_PUT_LOW_C4  		SYS_GPIO_PIN_Set(GPIOC, gpioPin4  , 0x00)    
#define 	OUT_PUT_LOW_C5  		SYS_GPIO_PIN_Set(GPIOC, gpioPin5  , 0x00)    
#define 	OUT_PUT_LOW_C6  		SYS_GPIO_PIN_Set(GPIOC, gpioPin6  , 0x00)    
#define 	OUT_PUT_LOW_C7  		SYS_GPIO_PIN_Set(GPIOC, gpioPin7  , 0x00)    
#define 	OUT_PUT_LOW_C8  		SYS_GPIO_PIN_Set(GPIOC, gpioPin8  , 0x00)    
#define 	OUT_PUT_LOW_C9  		SYS_GPIO_PIN_Set(GPIOC, gpioPin9  , 0x00)    
#define 	OUT_PUT_LOW_C10 		SYS_GPIO_PIN_Set(GPIOC, gpioPin10 , 0x00)    
#define 	OUT_PUT_LOW_C11			SYS_GPIO_PIN_Set(GPIOC, gpioPin11 , 0x00)    
#define 	OUT_PUT_LOW_C12      	SYS_GPIO_PIN_Set(GPIOC, gpioPin12 , 0x00)    
#define 	OUT_PUT_LOW_C13      	SYS_GPIO_PIN_Set(GPIOC, gpioPin13 , 0x00)    
#define 	OUT_PUT_LOW_C14      	SYS_GPIO_PIN_Set(GPIOC, gpioPin14 , 0x00)    
#define 	OUT_PUT_LOW_C15      	SYS_GPIO_PIN_Set(GPIOC, gpioPin15 , 0x00)
				   
#define 	OUT_PUT_LOW_D0  		SYS_GPIO_PIN_Set(GPIOD, gpioPin0  , 0x00)    
#define 	OUT_PUT_LOW_D1  		SYS_GPIO_PIN_Set(GPIOD, gpioPin1  , 0x00)    
#define 	OUT_PUT_LOW_D2  		SYS_GPIO_PIN_Set(GPIOD, gpioPin2  , 0x00)    
#define 	OUT_PUT_LOW_D3  		SYS_GPIO_PIN_Set(GPIOD, gpioPin3  , 0x00)    
#define 	OUT_PUT_LOW_D4  		SYS_GPIO_PIN_Set(GPIOD, gpioPin4  , 0x00)    
#define 	OUT_PUT_LOW_D5  		SYS_GPIO_PIN_Set(GPIOD, gpioPin5  , 0x00)    
#define 	OUT_PUT_LOW_D6  		SYS_GPIO_PIN_Set(GPIOD, gpioPin6  , 0x00)    
#define 	OUT_PUT_LOW_D7  		SYS_GPIO_PIN_Set(GPIOD, gpioPin7  , 0x00)    
#define 	OUT_PUT_LOW_D8  		SYS_GPIO_PIN_Set(GPIOD, gpioPin8  , 0x00)    
#define 	OUT_PUT_LOW_D9  		SYS_GPIO_PIN_Set(GPIOD, gpioPin9  , 0x00)    
#define 	OUT_PUT_LOW_D10 		SYS_GPIO_PIN_Set(GPIOD, gpioPin10 , 0x00)    
#define 	OUT_PUT_LOW_D11			SYS_GPIO_PIN_Set(GPIOD, gpioPin11 , 0x00)    
#define 	OUT_PUT_LOW_D12      	SYS_GPIO_PIN_Set(GPIOD, gpioPin12 , 0x00)    
#define 	OUT_PUT_LOW_D13      	SYS_GPIO_PIN_Set(GPIOD, gpioPin13 , 0x00)    
#define 	OUT_PUT_LOW_D14      	SYS_GPIO_PIN_Set(GPIOD, gpioPin14 , 0x00)    
#define 	OUT_PUT_LOW_D15      	SYS_GPIO_PIN_Set(GPIOD, gpioPin15 , 0x00)
				   
#define 	OUT_PUT_LOW_E0  		SYS_GPIO_PIN_Set(GPIOE, gpioPin0  , 0x00)    
#define 	OUT_PUT_LOW_E1  		SYS_GPIO_PIN_Set(GPIOE, gpioPin1  , 0x00)    
#define 	OUT_PUT_LOW_E2  		SYS_GPIO_PIN_Set(GPIOE, gpioPin2  , 0x00)    
#define 	OUT_PUT_LOW_E3  		SYS_GPIO_PIN_Set(GPIOE, gpioPin3  , 0x00)    
#define 	OUT_PUT_LOW_E4  		SYS_GPIO_PIN_Set(GPIOE, gpioPin4  , 0x00)    
#define 	OUT_PUT_LOW_E5  		SYS_GPIO_PIN_Set(GPIOE, gpioPin5  , 0x00)    
#define 	OUT_PUT_LOW_E6  		SYS_GPIO_PIN_Set(GPIOE, gpioPin6  , 0x00)    
#define 	OUT_PUT_LOW_E7  		SYS_GPIO_PIN_Set(GPIOE, gpioPin7  , 0x00)    
#define 	OUT_PUT_LOW_E8  		SYS_GPIO_PIN_Set(GPIOE, gpioPin8  , 0x00)    
#define 	OUT_PUT_LOW_E9  		SYS_GPIO_PIN_Set(GPIOE, gpioPin9  , 0x00)    
#define 	OUT_PUT_LOW_E10 		SYS_GPIO_PIN_Set(GPIOE, gpioPin10 , 0x00)    
#define 	OUT_PUT_LOW_E11			SYS_GPIO_PIN_Set(GPIOE, gpioPin11 , 0x00)    
#define 	OUT_PUT_LOW_E12      	SYS_GPIO_PIN_Set(GPIOE, gpioPin12 , 0x00)    
#define 	OUT_PUT_LOW_E13      	SYS_GPIO_PIN_Set(GPIOE, gpioPin13 , 0x00)    
#define 	OUT_PUT_LOW_E14      	SYS_GPIO_PIN_Set(GPIOE, gpioPin14 , 0x00)    
#define 	OUT_PUT_LOW_E15      	SYS_GPIO_PIN_Set(GPIOE, gpioPin15 , 0x00)
				   
#define 	OUT_PUT_LOW_F0  		SYS_GPIO_PIN_Set(GPIOF, gpioPin0  , 0x00)    
#define 	OUT_PUT_LOW_F1  		SYS_GPIO_PIN_Set(GPIOF, gpioPin1  , 0x00)    
#define 	OUT_PUT_LOW_F2  		SYS_GPIO_PIN_Set(GPIOF, gpioPin2  , 0x00)    
#define 	OUT_PUT_LOW_F3  		SYS_GPIO_PIN_Set(GPIOF, gpioPin3  , 0x00)    
#define 	OUT_PUT_LOW_F4  		SYS_GPIO_PIN_Set(GPIOF, gpioPin4  , 0x00)    
#define 	OUT_PUT_LOW_F5  		SYS_GPIO_PIN_Set(GPIOF, gpioPin5  , 0x00)    
#define 	OUT_PUT_LOW_F6  		SYS_GPIO_PIN_Set(GPIOF, gpioPin6  , 0x00)    
#define 	OUT_PUT_LOW_F7  		SYS_GPIO_PIN_Set(GPIOF, gpioPin7  , 0x00)    
#define 	OUT_PUT_LOW_F8  		SYS_GPIO_PIN_Set(GPIOF, gpioPin8  , 0x00)    
#define 	OUT_PUT_LOW_F9  		SYS_GPIO_PIN_Set(GPIOF, gpioPin9  , 0x00)    
#define 	OUT_PUT_LOW_F10 		SYS_GPIO_PIN_Set(GPIOF, gpioPin10 , 0x00)    
#define 	OUT_PUT_LOW_F11			SYS_GPIO_PIN_Set(GPIOF, gpioPin11 , 0x00)    
#define 	OUT_PUT_LOW_F12      	SYS_GPIO_PIN_Set(GPIOF, gpioPin12 , 0x00)    
#define 	OUT_PUT_LOW_F13      	SYS_GPIO_PIN_Set(GPIOF, gpioPin13 , 0x00)    
#define 	OUT_PUT_LOW_F14      	SYS_GPIO_PIN_Set(GPIOF, gpioPin14 , 0x00)    
#define 	OUT_PUT_LOW_F15      	SYS_GPIO_PIN_Set(GPIOF, gpioPin15 , 0x00)
				   
#define 	OUT_PUT_LOW_G0  		SYS_GPIO_PIN_Set(GPIOG, gpioPin0  , 0x00)    
#define 	OUT_PUT_LOW_G1  		SYS_GPIO_PIN_Set(GPIOG, gpioPin1  , 0x00)    
#define 	OUT_PUT_LOW_G2  		SYS_GPIO_PIN_Set(GPIOG, gpioPin2  , 0x00)    
#define 	OUT_PUT_LOW_G3  		SYS_GPIO_PIN_Set(GPIOG, gpioPin3  , 0x00)    
#define 	OUT_PUT_LOW_G4  		SYS_GPIO_PIN_Set(GPIOG, gpioPin4  , 0x00)    
#define 	OUT_PUT_LOW_G5  		SYS_GPIO_PIN_Set(GPIOG, gpioPin5  , 0x00)    
#define 	OUT_PUT_LOW_G6  		SYS_GPIO_PIN_Set(GPIOG, gpioPin6  , 0x00)    
#define 	OUT_PUT_LOW_G7  		SYS_GPIO_PIN_Set(GPIOG, gpioPin7  , 0x00)    
#define 	OUT_PUT_LOW_G8  		SYS_GPIO_PIN_Set(GPIOG, gpioPin8  , 0x00)    
#define 	OUT_PUT_LOW_G9  		SYS_GPIO_PIN_Set(GPIOG, gpioPin9  , 0x00)    
#define 	OUT_PUT_LOW_G10 		SYS_GPIO_PIN_Set(GPIOG, gpioPin10 , 0x00)    
#define 	OUT_PUT_LOW_G11			SYS_GPIO_PIN_Set(GPIOG, gpioPin11 , 0x00)    
#define 	OUT_PUT_LOW_G12      	SYS_GPIO_PIN_Set(GPIOG, gpioPin12 , 0x00)    
#define 	OUT_PUT_LOW_G13      	SYS_GPIO_PIN_Set(GPIOG, gpioPin13 , 0x00)    
#define 	OUT_PUT_LOW_G14      	SYS_GPIO_PIN_Set(GPIOG, gpioPin14 , 0x00)    
#define 	OUT_PUT_LOW_G15      	SYS_GPIO_PIN_Set(GPIOG, gpioPin15 , 0x00)
				   
#define 	OUT_PUT_LOW_H0  		SYS_GPIO_PIN_Set(GPIOH, gpioPin0  , 0x00)    
#define 	OUT_PUT_LOW_H1  		SYS_GPIO_PIN_Set(GPIOH, gpioPin1  , 0x00)    
#define 	OUT_PUT_LOW_H2  		SYS_GPIO_PIN_Set(GPIOH, gpioPin2  , 0x00)    
#define 	OUT_PUT_LOW_H3  		SYS_GPIO_PIN_Set(GPIOH, gpioPin3  , 0x00)    
#define 	OUT_PUT_LOW_H4  		SYS_GPIO_PIN_Set(GPIOH, gpioPin4  , 0x00)    
#define 	OUT_PUT_LOW_H5  		SYS_GPIO_PIN_Set(GPIOH, gpioPin5  , 0x00)    
#define 	OUT_PUT_LOW_H6  		SYS_GPIO_PIN_Set(GPIOH, gpioPin6  , 0x00)    
#define 	OUT_PUT_LOW_H7  		SYS_GPIO_PIN_Set(GPIOH, gpioPin7  , 0x00)    
#define 	OUT_PUT_LOW_H8  		SYS_GPIO_PIN_Set(GPIOH, gpioPin8  , 0x00)    
#define 	OUT_PUT_LOW_H9  		SYS_GPIO_PIN_Set(GPIOH, gpioPin9  , 0x00)    
#define 	OUT_PUT_LOW_H10 		SYS_GPIO_PIN_Set(GPIOH, gpioPin10 , 0x00)    
#define 	OUT_PUT_LOW_H11			SYS_GPIO_PIN_Set(GPIOH, gpioPin11 , 0x00)    
#define 	OUT_PUT_LOW_H12      	SYS_GPIO_PIN_Set(GPIOH, gpioPin12 , 0x00)    
#define 	OUT_PUT_LOW_H13      	SYS_GPIO_PIN_Set(GPIOH, gpioPin13 , 0x00)    
#define 	OUT_PUT_LOW_H14      	SYS_GPIO_PIN_Set(GPIOH, gpioPin14 , 0x00)    
#define 	OUT_PUT_LOW_H15      	SYS_GPIO_PIN_Set(GPIOH, gpioPin15 , 0x00)
				   
#define 	OUT_PUT_LOW_I0  		SYS_GPIO_PIN_Set(GPIOI, gpioPin0  , 0x00)    
#define 	OUT_PUT_LOW_I1  		SYS_GPIO_PIN_Set(GPIOI, gpioPin1  , 0x00)    
#define 	OUT_PUT_LOW_I2  		SYS_GPIO_PIN_Set(GPIOI, gpioPin2  , 0x00)    
#define 	OUT_PUT_LOW_I3  		SYS_GPIO_PIN_Set(GPIOI, gpioPin3  , 0x00)    
#define 	OUT_PUT_LOW_I4  		SYS_GPIO_PIN_Set(GPIOI, gpioPin4  , 0x00)    
#define 	OUT_PUT_LOW_I5  		SYS_GPIO_PIN_Set(GPIOI, gpioPin5  , 0x00)    
#define 	OUT_PUT_LOW_I6  		SYS_GPIO_PIN_Set(GPIOI, gpioPin6  , 0x00)    
#define 	OUT_PUT_LOW_I7  		SYS_GPIO_PIN_Set(GPIOI, gpioPin7  , 0x00)    
#define 	OUT_PUT_LOW_I8  		SYS_GPIO_PIN_Set(GPIOI, gpioPin8  , 0x00)    
#define 	OUT_PUT_LOW_I9  		SYS_GPIO_PIN_Set(GPIOI, gpioPin9  , 0x00)    
#define 	OUT_PUT_LOW_I10 		SYS_GPIO_PIN_Set(GPIOI, gpioPin10 , 0x00)    
#define 	OUT_PUT_LOW_I11			SYS_GPIO_PIN_Set(GPIOI, gpioPin11 , 0x00)    
#define 	OUT_PUT_LOW_I12      	SYS_GPIO_PIN_Set(GPIOI, gpioPin12 , 0x00)    
#define 	OUT_PUT_LOW_I13      	SYS_GPIO_PIN_Set(GPIOI, gpioPin13 , 0x00)    
#define 	OUT_PUT_LOW_I14      	SYS_GPIO_PIN_Set(GPIOI, gpioPin14 , 0x00)    
#define 	OUT_PUT_LOW_I15      	SYS_GPIO_PIN_Set(GPIOI, gpioPin15 , 0x00)

/*==============================================================
*FUNCTION NAME:
*DISCRIPTION:设置IO状态
*PARAMETERS:
*RETURN:
*N/A
*NOTES:
*HISTORY:
*==============================================================*/
void SYS_GPIO_PIN_Set(GPIO_TypeDef *p_gpiox, uint16_t pinx, uint8_t status);
/*==============================================================
*FUNCTION NAME:
*DISCRIPTION:读取IO状态
*PARAMETERS:
*RETURN:
*N/A
*NOTES:
*HISTORY:
*==============================================================*/
uint8_t SYS_GPIO_PIN_Get(GPIO_TypeDef *p_gpiox, uint16_t pinx);
/*==============================================================
*FUNCTION NAME:
*DISCRIPTION:IO翻转
*PARAMETERS:
*RETURN:
*N/A
*NOTES:
*HISTORY:
*==============================================================*/
void SYS_GPIO_TogglePin(GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin);				//io翻转




#endif
